### ISSUE TITLE
Google Ads Customer Match upload issue - tentacles

### ISSUE THREAD

**Issue by LukaData** [GoogleCloudPlatform/cloud-for-marketing#36]
I've been receiving an error across multiple tests (new installation, existing installation, different Google Ads accounts) in the final step (tentacles_api) of hashed email upload to Google Ads.

The input file is a copy of the "Sample Data file content" from the documentation. Single line hashed_email jsonl.

`[API.ADS] Error in Customer Match upload batch[3646537312283590-0-0] TypeError: Cannot read property 'replace' of undefined
    at GoogleAds.uploadUserDataToUserList (/workspace/node_modules/@google-cloud/nodejs-common/src/apis/google_ads.js:531:67)
    at /workspace/node_modules/@google-cloud/nodejs-common/src/apis/google_ads.js:499:37
    at /workspace/node_modules/@google-cloud/nodejs-common/src/components/utils.js:278:25
    at Array.map (<anonymous>)
    at sendSingleRound (/workspace/node_modules/@google-cloud/nodejs-common/src/components/utils.js:277:36)
    at reduceFn (/workspace/node_modules/@google-cloud/nodejs-common/src/components/utils.js:342:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /workspace/node_modules/@google-cloud/nodejs-common/src/components/utils.js:348:24
    at async sendApiData (/workspace/src/tentacles.js:411:20)`

**Comment by lushu** [comment]
Hi Luka,

First, please update to the latest version.
Then check the [configuration](https://github.com/GoogleCloudPlatform/cloud-for-marketing/tree/main/marketing-analytics/activation/gmp-googleads-connector#48-acm-google-ads-customer-match-upload-via-api) of this integration, especially the properties `customer_id` and `login_customer_id`.  It looks like one of these is missing?

**Comment by lushu** [comment]
I will close this now. Please re-open it if you still have issues.
