### ISSUE TITLE
Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by RuslanBergenov** [GoogleCloudPlatform/cloud-for-marketing#46]
After upgrading to the latest Tentacles version, I'm having the following errors when sending data to Google Ads API.

I reinstalled Tentacles on Friday, Sep 29. 

I can't downgrade Tentacles because I was getting some Google Ads API deprecation errors (v.12 deprecated) - that's why I reinstalled Tentacles. 

I am not sure yet if the data is coming through to Google Ads or not, I need some more time to test but it's likely that the data is not coming though.

tentacles_api Cloud Function fails with the error below. 

```
Error: Process exited with code 16
    at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:92:22)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
    at process.exit (internal/process/per_thread.js:179:15)
    at sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:44:9)
    at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:88:44)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (/workspace/node_modules/google-ads-node/node_modules/@grpc/grpc-js/build/src/channel.js:28:19)
    at new Client (/workspace/node_modules/google-ads-node/node_modules/@grpc/grpc-js/build/src/client.js:65:36)
    at new ServiceClientImpl (/workspace/node_modules/google-ads-node/node_modules/@grpc/grpc-js/build/src/make-client.js:58:5)
    at GrpcClient.createStub (/workspace/node_modules/google-ads-node/node_modules/google-gax/build/src/grpc.js:334:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Please let me know if you have any questions or need any more information.

Anyone else experienced the same error? Any insight on what the root cause might be?

**Comment by lushu** [comment]
Do you use the bash script or Google Sheets to installed the latest version? Is the version number v4.0.2?

**Comment by RuslanBergenov** [comment]
Thank you for getting back to me. I used the bash script to install. I didn't set the install to any specific version, so it must have pulled the latest code as of this Friday.

**Comment by lushu** [comment]
Can you check out the code and try again? 
BTW, you can just run ` ./deploy.sh deploy_cloud_functions_api_requester` to deploy the only Cloud Functions that is affected by this issue.

**Comment by RuslanBergenov** [comment]
Thanks so much for your prompt help @lushu, I will test on Monday and report back.

**Comment by RuslanBergenov** [comment]
@lushu , I just tested. 

I cloned the repo and ran ./deploy.sh deploy_cloud_functions_api_requester. 

I tried sending 1 row of data to Google Ads API and got a new error:` Required OAuth token does not exist.`

Error traceback is below.

Should I try reinstalling Tentacles from scratch again, the whole process? I remember that process would ask me about OAuth cliend id and secret. 

tentacles_api
[API.ADS] Error in uploadClickConversions batch: 9290853819365672-0-0 Error: Required OAuth token does not exist.
    at AuthClient.ensureCredentialExists_ (/workspace/node_modules/@google-cloud/nodejs-common/src/apis/auth_client.js:228:28)
    at AuthClient.getOAuth2Token (/workspace/node_modules/@google-cloud/nodejs-common/src/apis/auth_client.js:208:10)
    at GoogleAds.getGoogleAdsApiCustomer_ (/workspace/node_modules/@google-cloud/nodejs-common/src/apis/google_ads.js:1080:47)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async GoogleAds.uploadClickConversions (/workspace/node_modules/@google-cloud/nodejs-common/src/apis/google_ads.js:609:22)
    at async /workspace/node_modules/@google-cloud/nodejs-common/src/apis/google_ads.js:424:26
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async sendSingleRound (/workspace/node_modules/@google-cloud/nodejs-common/src/components/utils.js:278:26)
    at async reduceFn (/workspace/node_modules/@google-cloud/nodejs-common/src/components/utils.js:341:11)

**Comment by RuslanBergenov** [comment]
I reinstalled Tentacles using these commands:

```
git clone https://github.com/GoogleCloudPlatform/cloud-for-marketing.git
cd cloud-for-marketing/marketing-analytics/activation/gmp-googleads-connector
bash deploy.sh
```
The process asked me to supply OAuth client id and secret. 

Some quick tests after that passed: the two errors discussed above are gone now. 

We can close this issue out. Thank you for implementing the fix so quickly.
